In [1]:
l=[2,3.4,'Madhu']
l.append(4.5)
l

[2, 3.4, 'Madhu', 4.5]

In [2]:
l.append([65,'Science'])
l

[2, 3.4, 'Madhu', 4.5, [65, 'Science']]

In [2]:
l.extend([3,4])
l

[2, 3.4, 'Madhu', 4.5, 3, 4]

In [4]:
l.insert(4,'Javvaji')
l

[2, 3.4, 'Javvaji', 'Madhu', 'Javvaji', 4.5, 3, 4]

In [5]:
l.remove('Javvaji')
l

[2, 3.4, 'Madhu', 'Javvaji', 4.5, 3, 4]

In [6]:
l.remove('Javvaji')
l

[2, 3.4, 'Madhu', 4.5, 3, 4]

In [9]:
l.append(4)
l.count(4)


2

In [10]:
l

[2, 3.4, 'Madhu', 4.5, 3, 4, 4]

In [11]:
l.reverse()
l

[4, 4, 3, 4.5, 'Madhu', 3.4, 2]

In [25]:
l

[2, 'Madhu', 4.5, [65, 'Science'], 3, 4]

In [26]:
l.reverse()

In [27]:
l

[4, 3, [65, 'Science'], 4.5, 'Madhu', 2]

In [17]:
x=[[1,2,3],[4,5,6],[7,8,9]]
import numpy as np
y=np.array(x)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.random.randint(10,100,(10,5))

array([[64, 47, 58, 89, 32],
       [31, 61, 16, 72, 93],
       [36, 38, 95, 20, 25],
       [51, 65, 25, 66, 44],
       [63, 91, 86, 65, 98],
       [50, 44, 56, 50, 19],
       [23, 93, 65, 74, 18],
       [77, 26, 29, 12, 77],
       [57, 36, 48, 14, 40],
       [69, 14, 35, 31, 81]])

In [30]:
x=np.random.randint(35,100,(100,5))
x

array([[90, 95, 59, 90, 88],
       [89, 47, 40, 91, 73],
       [81, 98, 50, 36, 36],
       [84, 54, 55, 51, 55],
       [88, 95, 45, 60, 95],
       [64, 96, 72, 81, 35],
       [82, 95, 65, 37, 92],
       [84, 92, 74, 56, 74],
       [76, 92, 70, 63, 76],
       [91, 59, 79, 69, 74],
       [85, 88, 87, 57, 48],
       [85, 72, 61, 42, 47],
       [63, 71, 65, 59, 72],
       [72, 79, 89, 85, 65],
       [76, 53, 42, 99, 52],
       [45, 96, 37, 88, 75],
       [92, 47, 48, 92, 50],
       [66, 68, 55, 46, 82],
       [89, 95, 44, 46, 51],
       [95, 97, 84, 76, 38],
       [40, 92, 94, 41, 83],
       [45, 74, 99, 76, 52],
       [59, 39, 78, 78, 51],
       [93, 75, 83, 41, 88],
       [89, 63, 76, 73, 50],
       [99, 97, 39, 68, 52],
       [60, 64, 49, 86, 42],
       [63, 83, 68, 46, 53],
       [72, 76, 44, 59, 71],
       [82, 88, 83, 38, 54],
       [46, 77, 38, 38, 65],
       [36, 73, 38, 37, 58],
       [73, 64, 40, 53, 50],
       [61, 83, 65, 63, 63],
       [58, 78

In [18]:
d=(x[0]-x)*(x[0]-x)
fd=np.sqrt(d.sum(axis=1))

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [37]:
fd

array([ 0.        , 53.77731864, 76.09862022, 65.90144156, 33.89690251,
       61.12282716, 54.08326913, 40.27406113, 34.62657939, 48.31148932,
       59.55669568, 67.40178039, 50.57667447, 45.09988914, 60.21627687,
       51.79768335, 62.2655603 , 57.38466694, 59.42221807, 57.87918451,
       78.48566748, 74.55199528, 77.27224599, 58.1893461 , 55.19963768,
       47.59201614, 63.97655821, 64.14826576, 46.47580015, 67.44627492,
       77.03246069, 86.89073598, 66.51315659, 48.73397172, 51.01960408,
       71.08445681, 78.02563681, 49.86983056, 47.0637865 , 66.64082833,
       51.74939613, 59.27900134, 77.57576941, 78.52388172, 62.31372241,
       98.12237258, 31.9217794 , 32.17141588, 62.64183905, 40.17461885,
       79.66806135, 59.27900134, 64.82283548, 83.49251463, 71.86793444,
       80.56053624, 41.46082488, 58.05170109, 70.13558298, 93.60021367,
       69.8140387 , 93.25234581, 38.31448812, 32.95451411, 54.69003566,
       73.34166619, 72.06941099, 59.40538696, 70.22107946, 62.85

In [38]:
fd[1:].min()

20.199009876724155

In [39]:
fd[1:].argmin()

71

In [28]:
bdb= np.random.randint(35,100,(100,5))
bdb[:,0]

array([35, 49, 81, 48, 89, 77, 44, 85, 45, 55, 74, 60, 37, 55, 74, 86, 35,
       55, 45, 61, 55, 35, 77, 90, 42, 36, 87, 65, 51, 41, 95, 95, 76, 98,
       70, 84, 81, 37, 47, 40, 92, 71, 55, 47, 62, 46, 65, 82, 55, 86, 57,
       55, 54, 86, 63, 45, 89, 50, 61, 91, 54, 72, 41, 92, 68, 90, 48, 57,
       41, 60, 90, 62, 67, 96, 63, 78, 88, 56, 89, 88, 58, 75, 58, 60, 76,
       98, 36, 82, 53, 61, 78, 60, 67, 42, 91, 80, 69, 96, 49, 53])

In [29]:
bdb[:,0]=np.random.randint(0,2,100)
bdb[:,0]

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1])

In [30]:
bdb[:,1]=np.random.randint(40000,70000,100)
bdb[:,1]

array([56714, 67945, 62832, 62083, 53038, 54717, 44215, 50512, 46049,
       50513, 65388, 68728, 49563, 52002, 67958, 55620, 60827, 42144,
       47840, 45072, 64974, 49966, 60195, 45729, 59621, 45661, 62967,
       46104, 55835, 68381, 51714, 51450, 43784, 46373, 45577, 66526,
       67537, 53434, 58204, 48283, 50002, 54393, 45272, 47188, 50193,
       63800, 58790, 52603, 65080, 65192, 63569, 68054, 49340, 43713,
       64377, 62624, 40627, 63489, 49584, 61531, 42096, 41541, 47996,
       56559, 63094, 48262, 50842, 66061, 57984, 44199, 45260, 46613,
       57956, 65013, 57505, 46631, 57656, 61426, 60245, 55299, 45234,
       56030, 59533, 56140, 66515, 60405, 55189, 69810, 68518, 52868,
       48865, 55418, 56265, 64904, 52573, 54944, 60929, 41442, 44021,
       55147])

In [31]:
bdb[:,2]=np.random.randint(4,10,100)
bdb[:,2]

array([9, 7, 9, 7, 6, 5, 5, 4, 9, 9, 5, 5, 4, 8, 8, 4, 6, 4, 5, 7, 4, 5,
       9, 8, 7, 8, 6, 5, 7, 6, 5, 7, 9, 9, 8, 7, 5, 5, 6, 9, 9, 4, 8, 5,
       9, 9, 7, 4, 7, 9, 6, 7, 9, 4, 5, 8, 9, 8, 9, 9, 6, 7, 9, 4, 6, 6,
       4, 6, 8, 5, 6, 8, 5, 9, 7, 8, 9, 7, 8, 9, 4, 5, 6, 9, 9, 8, 5, 5,
       6, 6, 6, 8, 6, 4, 6, 8, 6, 6, 8, 7])

In [32]:
bdb[:,3]=np.random.randint(25,40,100)
bdb[:,3]

array([36, 25, 38, 28, 35, 36, 37, 35, 30, 26, 28, 38, 39, 37, 36, 34, 28,
       39, 30, 31, 35, 32, 37, 31, 28, 30, 35, 38, 39, 26, 29, 30, 27, 25,
       27, 38, 36, 38, 34, 33, 33, 34, 34, 35, 28, 28, 27, 32, 33, 32, 29,
       28, 37, 31, 38, 32, 34, 31, 38, 30, 26, 32, 31, 29, 30, 27, 33, 32,
       28, 38, 25, 36, 33, 32, 25, 29, 39, 33, 33, 38, 31, 25, 26, 31, 25,
       31, 33, 26, 34, 33, 34, 33, 38, 34, 33, 35, 26, 37, 27, 38])

In [33]:
bdb[:,4]=np.random.randint(1,5,100)
bdb[:,4]

array([3, 1, 3, 3, 4, 3, 4, 3, 4, 1, 2, 2, 2, 2, 4, 2, 4, 3, 3, 1, 1, 1,
       2, 3, 1, 1, 4, 3, 4, 1, 2, 1, 2, 3, 3, 3, 1, 3, 1, 4, 2, 3, 3, 4,
       3, 2, 1, 1, 3, 4, 3, 1, 3, 2, 2, 4, 3, 2, 3, 2, 3, 1, 1, 2, 1, 4,
       1, 3, 2, 2, 4, 2, 2, 2, 4, 3, 4, 4, 4, 4, 4, 2, 1, 4, 2, 1, 4, 4,
       2, 2, 4, 3, 3, 1, 1, 1, 3, 1, 4, 3])

In [34]:
test=np.array([40000,7,30,2])

In [35]:
test

array([40000,     7,    30,     2])

In [48]:
d=(bdb[:,1:]-test)*(bdb[:,1:]-test)
d
fd=np.sqrt(d.sum(axis=1))
fd
##fd.min(),fd.argmin()

array([16714.00122652, 27945.0004652 , 22832.00151104, 22083.00011321,
       13038.00115048, 14717.00139295,  4215.00676156, 10512.00166476,
        6049.00066127, 10513.00099876, 25388.00015755, 28728.00118351,
        9563.00470564, 12002.00208299, 27958.00073324, 15620.00080026,
       20827.00021607,  2144.02122191,  7840.00031888,  5072.00019716,
       24974.00070073,  9966.00045154, 20195.00131221,  5729.00026183,
       19621.00012741,  5661.00017665, 22967.00065311,  6104.00565203,
       15835.00268393, 28381.00031711, 11714.00021342, 11450.00004367,
        3784.00171776,  6373.00235368,  5577.00098619, 26526.00122521,
       27537.00074445, 13434.00256811, 18204.0004944 ,  8283.0010262 ,
       10002.00064987, 14393.00090322,  5272.00170713,  7188.00229549,
       10193.00044148, 23800.00016807, 18790.0002661 , 12603.00055542,
       25080.00019936, 25192.00023817, 23569.00006364, 28054.00008911,
        9340.00289079,  3713.00134662, 24377.00139476, 22624.0001989 ,
      

In [47]:
bdb

array([[    0, 56714,     9,    36,     3],
       [    0, 67945,     7,    25,     1],
       [    0, 62832,     9,    38,     3],
       [    0, 62083,     7,    28,     3],
       [    0, 53038,     6,    35,     4],
       [    1, 54717,     5,    36,     3],
       [    1, 44215,     5,    37,     4],
       [    0, 50512,     4,    35,     3],
       [    1, 46049,     9,    30,     4],
       [    1, 50513,     9,    26,     1],
       [    0, 65388,     5,    28,     2],
       [    0, 68728,     5,    38,     2],
       [    0, 49563,     4,    39,     2],
       [    1, 52002,     8,    37,     2],
       [    1, 67958,     8,    36,     4],
       [    0, 55620,     4,    34,     2],
       [    0, 60827,     6,    28,     4],
       [    0, 42144,     4,    39,     3],
       [    1, 47840,     5,    30,     3],
       [    1, 45072,     7,    31,     1],
       [    0, 64974,     4,    35,     1],
       [    1, 49966,     5,    32,     1],
       [    0, 60195,     9,    

In [72]:
## Loops

In [73]:
x=10
if x>3:
    print('Madhu')

Madhu


In [77]:
if True:
    print('Madhu')

Madhu


In [78]:
if 1:
    print('True')

True


In [82]:
if 0:
    print('True')

In [83]:
if 2:
    print('True')

True


In [84]:
if 3.4:
    print('Madhu')

Madhu


In [85]:
x=input()

Madhu


In [86]:
x=input(input())

Madhu
Madhu32


In [87]:
x

'32'

In [89]:
x=int(input())
if x>10:
    print('True')
else:
    print('False')

2
False


In [90]:
x=int(input())
if x>10:
    print('Rank1')
elif x<20 & x>30:
    print('Rank2')
elif x<=30 & x>=40:
    print('Rank3')

30
Rank1


In [91]:
x=input()

Madhu


In [92]:
x

'Madhu'

In [93]:
type(x)

str

In [94]:
x=input()

10


In [95]:
x

'10'

In [96]:
type(x)

str

In [106]:
x=np.array(["Madhu","Bharat"])
for M in x:
    print(M)

Madhu
Bharat


In [107]:
print('Madhu')

Madhu
