In [3]:
x="I like data science"
for M in x.split():
    print(M.capitalize())

I
Like
Data
Science


In [9]:
x="I like data science"
for M in x.split():
    print(M.capitalize(),len(M))

I 1
Like 4
Data 4
Science 7


In [20]:
x= "This is my true review on Amazon Amazon is the Indias largest, $ online shopping company which has % different different kinds of product I am also buying such & kind of product but I am not # satisfied there product theseare the very cheap in quality and Amazon charge high price for this product disappointing from their their services thecustomer support service is very bad they cant even pick up the call for any queries cant take any 1 action on the 2 customers problem the quality of the product is the worst which I have ever seen delivery service of Amazon is also worst because they said for 4 to 3 days for delivery but they take one to two weeks which is very slow I cant like Amazon app because they cant show full description of the product. This app is not reliable for anyone purchase of @ something product is totally waste of money"

In [22]:
for M in x:
    if M.isalpha() == False:
        print(M)

 
 
 
 
 
 
 
 
 
 
,
 
$
 
 
 
 
 
 
%
 
 
 
 
 
 
 
 
 
 
 
&
 
 
 
 
 
 
 
 
#
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
1
 
 
 
 
2
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
4
 
 
3
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
.
 
 
 
 
 
 
 
 
 
 
@
 
 
 
 
 
 
 


In [24]:
SP=[]
for M in x:
    if M.isalpha() == False:
        SP.append(M)      

In [25]:
SP

[' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ',',
 ' ',
 '$',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '%',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '&',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '#',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1',
 ' ',
 ' ',
 ' ',
 ' ',
 '2',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '4',
 ' ',
 ' ',
 '3',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '.',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '@',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' '

In [30]:
EvenL=[]
OddL=[]
for M in x.split():
    if len(M)%2==0:
        EvenL.append(M)
    else:
        OddL.append(M)

In [32]:
EvenL, OddL

(['This',
  'is',
  'my',
  'truereview',
  'on',
  'Amazon',
  'Amazon',
  'is',
  'Indias',
  'largest,',
  'online',
  'shopping',
  'of',
  'am',
  'also',
  'buying',
  'such',
  'kind',
  'of',
  'am',
  'theseare',
  'very',
  'in',
  'Amazon',
  'charge',
  'high',
  'this',
  'from',
  'services',
  'is',
  'very',
  'they',
  'cant',
  'even',
  'pick',
  'up',
  'call',
  'cant',
  'take',
  'action',
  'on',
  'of',
  'is',
  'have',
  'ever',
  'seen',
  'delivery',
  'of',
  'Amazon',
  'is',
  'also',
  'they',
  'said',
  'to',
  'days',
  'delivery',
  'they',
  'take',
  'to',
  'is',
  'very',
  'slow',
  'cant',
  'like',
  'Amazon',
  'they',
  'cant',
  'show',
  'full',
  'of',
  'product.',
  'This',
  'is',
  'reliable',
  'anyone',
  'purchase',
  'of',
  'is',
  'of'],
 ['the',
  '$',
  'company',
  'which',
  'has',
  '%',
  'different',
  'different',
  'kinds',
  'product',
  'I',
  '&',
  'product',
  'but',
  'I',
  'not',
  '#',
  'satisfied',
  'there'

In [7]:
x="Product is awesome"
for i in range(0,len(x)+1):
    print(x[0:i])
    


P
Pr
Pro
Prod
Produ
Produc
Product
Product 
Product i
Product is
Product is 
Product is a
Product is aw
Product is awe
Product is awes
Product is aweso
Product is awesom
Product is awesome


In [9]:
import numpy as np
x="Product is awesome"
for i in np.arange(0,len(x)+1):
    print(x[0:i])


P
Pr
Pro
Prod
Produ
Produc
Product
Product 
Product i
Product is
Product is 
Product is a
Product is aw
Product is awe
Product is awes
Product is aweso
Product is awesom
Product is awesome


In [11]:
x=np.random.randint(0,100,(3,4))
x

array([[64, 23, 93, 33],
       [47, 20, 47, 11],
       [ 9, 69, 28, 25]])

In [38]:
distance=[]
for i in x:
    for j in x:
        d=np.sqrt(((i-j)*(i-j)).sum())
        distance.append(d)

In [45]:
distance

[0.0,
 59.23681287847955,
 93.24698386543128,
 59.23681287847955,
 0.0,
 62.51399843235114,
 93.24698386543128,
 62.51399843235114,
 0.0]

In [47]:
Md=np.array(distance)
Md.reshape(3,3)

array([[ 0.        , 59.23681288, 93.24698387],
       [59.23681288,  0.        , 62.51399843],
       [93.24698387, 62.51399843,  0.        ]])

In [48]:
MD=[2,6,'Data','Anyl',43,12.3]

In [53]:
Number=[]
for i in MD:
    if str(i).isdigit():
        Number.append(i)

In [56]:
D= np.array(Number)
D.sum()

51

In [58]:
D

array([ 2,  6, 43])

In [100]:
p="Data science Machine Learning"
x=''
for i in p.split():
    x=x+i[::-1]


In [101]:
x

'ataDecneicsenihcaMgninraeL'

In [108]:
x="Wikipedia is written collaboratively by largely anonymous volunteers who write without pay. Anyone with Internet access can write and make changes to Wikipedia articles, except in limited cases where editing is restricted to prevent disruption or vandalism. Users can contribute anonymously, under a pseudonym, or, if they choose to, with their real identity. The fundamental principles by which Wikipedia operates are the five pillars. The Wikipedia community has developed many policies and guidelines to improve the encyclopedia; however, it is not a formal requirement to be familiar with them before contributing. Since its creation on January 15, 2001, Wikipedia has grown rapidly into one of the largest reference websites, attracting 374 million unique visitors monthly as of September 2015.[1] There are about 72,000 active contributors working on more than 48,000,000 articles in 302 languages. As of today, there are 5,949,193 articles in English. Every day, hundreds of thousands of visitors from around the word collectively make tens of thousands of edits and create thousands of new articles to augment the knowledge held by the Wikipedia encyclopedia. (See the statistics page for more information.) People of all ages, cultures and backgrounds can add or edit article prose, references, images and other media here. What is contributed is more important than the expertise or qualifications of the contributor. What will remain depends upon whether the content is free of copyright restrictions and contentious material about living people, and whether it fits within Wikipedia's policies, including being verifiable against a published reliable source, thereby excluding editors' opinions and beliefs and unreviewed research. Contributions cannot damage Wikipedia because the software allows easy reversal of mistakes and many experienced editors are watching to help ensure that edits are cumulative improvements. Begin by simply clicking the Edit link at the top of any editable page!Wikipedia is a live collaboration differing from paper-based reference sources in important ways. Unlike printed encyclopedias, Wikipedia is continually created and updated, with articles on historic events appearing within minutes, rather than months or years. Because everybody can help improve it, Wikipedia has become more comprehensive than any other encyclopedia. In addition to quantity, its contributors work on improving quality as well. Wikipedia is a work-in-progress, with articles in various stages of completion. As articles develop, they tend to become more comprehensive and balanced. Quality also improves over time as misinformation and other errors are removed or repaired. However, because anyone can click at any time and add content, any article may contain undetected misinformation, errors, or vandalism. Awareness of this helps the reader to obtain valid information, avoid recently added misinformation (see Wikipedia : Researching with Wikipedia), and fix the article"

In [109]:
Data = []
for i in x.split():
    if i == 'is':
        Data.append(i)

In [111]:
len(Data)/len(x)

0.003002001334222815

[100, 7, 5, 6]
