In [ ]:
## math.factorial - it gives a factorial of given number
## math.floor - it returns the largest integer less then or equal to the original value
## math.ceil - it returns the largest integer greter then equal to original integer
## math.exp - it returns the expnential value
## math.expm1(x) - 
## math.log2(x) -

In [2]:
x= int(input())

5.8


ValueError: invalid literal for int() with base 10: '5.8'

In [8]:
import math
x = 3.1

In [9]:
math.floor(x)

3

In [10]:
math.ceil(x)

4

In [11]:
y= float(input())

6.7


In [13]:
math.exp(y)

812.4058251675433

In [16]:
math.factorial(5 )

120

In [17]:
math.expm1(y)

811.4058251675433

In [18]:
math.log(x)

1.1314021114911006

In [19]:
math.log(y)

1.9021075263969205

In [20]:
math.e

2.718281828459045

In [21]:
math.pow(2,3)

8.0

In [22]:
math.sqrt(4)

2.0

In [23]:
math.sqrt(y)

2.588435821108957

In [24]:
math.pi

3.141592653589793

In [25]:
math.log(y)

1.9021075263969205

In [26]:
math.tau

6.283185307179586

In [27]:
math.e

2.718281828459045

In [28]:
math.factorial(x)

ValueError: factorial() only accepts integral values

In [29]:
math.cos(1)

0.5403023058681398

In [30]:
math.sin(1)

0.8414709848078965

In [31]:
math.tan(1)

1.5574077246549023

In [32]:
## math.cosh()
## math.sinh()
## math.tanh()
## math.acos()
## math.asin()
## math.atan()

In [33]:
## Function
## list || Numpy

In [34]:
a = [23,4.4,'Data science']

In [35]:
a[0]

23

In [36]:
a[0:2]

[23, 4.4]

In [37]:
a[-1]

'Data science'

In [38]:
type(a)

list

In [39]:
b=[2,3,6]

In [40]:
b/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [41]:
import numpy as np

In [42]:
z=np.array(b)

In [43]:
z/2

array([1. , 1.5, 3. ])

In [44]:
np.array(a)

array(['23', '4.4', 'Data science'], dtype='<U32')

In [45]:
x=np.array([[2,3,4],[65,7,76],[43,2,45]])

In [46]:
x

array([[ 2,  3,  4],
       [65,  7, 76],
       [43,  2, 45]])

In [47]:
x.sum()

247

In [48]:
x.min()

2

In [49]:
x.max()

76

In [50]:
x.mean()

27.444444444444443

In [51]:
x.sum(axis=1)

array([  9, 148,  90])

In [52]:
x.sum(axis=0)

array([110,  12, 125])

In [53]:
x

array([[ 2,  3,  4],
       [65,  7, 76],
       [43,  2, 45]])

In [54]:
x[0:2].sum()

157

In [55]:
x.argmin() ## position of the min value

0

In [56]:
x.argmax() ## position of the max value

5

In [57]:
x[:,2]

array([ 4, 76, 45])

In [58]:
x[:,2:]

array([[ 4],
       [76],
       [45]])

In [59]:
np.random.randint(0,10,10)

array([8, 5, 2, 7, 7, 7, 8, 6, 9, 9])

In [60]:
z = np.random.randint(0,100,(10,10))
z

array([[29,  9, 15, 93, 82, 53, 29, 11, 47, 47],
       [41, 34, 10, 69, 97, 41, 42, 43, 86, 86],
       [ 8, 24, 60, 22, 75, 34, 11, 29, 82, 35],
       [82, 84, 62, 51,  4, 42, 30, 44, 28, 30],
       [ 7, 17, 37, 10, 17, 42, 63, 79, 73, 36],
       [24, 56, 79, 75, 10, 42, 19, 10, 88, 83],
       [ 0, 10, 75, 63, 27, 25, 68, 85, 71, 28],
       [68, 63, 27, 63, 84, 33, 51, 73, 62, 81],
       [99, 56, 52, 91, 47, 63, 42, 21, 34, 30],
       [35, 40, 89, 22, 77, 23, 98, 59, 39, 81]])

In [61]:
CB = np.random.randint(10,100,(100,5)) ## we have 100 customers purchased 5 products in the range of 10$ to 100$


In [62]:
x=CB.sum(axis=1)
x

array([251, 188, 245, 303, 255, 261, 249, 240, 266, 238, 253, 232, 191,
       222, 371, 273, 311, 353, 185, 337, 248, 263, 340, 161, 285, 259,
       159, 190, 369, 282, 414, 301, 238, 280, 242, 364, 287, 301, 358,
       209, 377, 355, 330, 134, 237, 306, 363, 373, 235, 235, 122, 306,
       330, 259, 406, 256, 259, 375, 255, 229, 214, 323, 273, 322, 267,
       261, 208, 235, 310, 384, 326, 277, 331, 250, 301, 310, 389, 208,
       265, 207, 267, 263, 282, 331, 312, 330, 250, 237, 266, 358, 311,
       237, 365, 196, 365, 356, 192, 292, 243, 125])

In [63]:
x.min(),x.max(),x.argmin(),x.argmax()

(122, 414, 50, 30)

In [101]:
x[x.argmin()]

149

In [107]:
x=np.random.randint(5,10,(5,10))
x

array([[5, 8, 8, 8, 7, 5, 8, 6, 8, 9],
       [6, 8, 8, 6, 9, 8, 6, 8, 7, 6],
       [5, 9, 6, 6, 7, 6, 5, 9, 7, 5],
       [8, 8, 8, 6, 5, 7, 6, 8, 7, 6],
       [5, 5, 7, 8, 7, 8, 6, 5, 5, 5]])

In [112]:
x[x.argmin()]

array([5, 8, 8, 8, 7, 5, 8, 6, 8, 9])

In [113]:
x[x.argmax()]

IndexError: index 9 is out of bounds for axis 0 with size 5

In [122]:
##np.arange(0,10),
##np.random.randint(0,10,(10,10)),
##np.zeros(10),
##np.zeros((10,10)),
##np.ones(10),
##np.ones((10,10)),
##np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [116]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [117]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [118]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [119]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [120]:
np.random.randint(0,10,(10,10))

array([[2, 3, 9, 1, 4, 0, 4, 4, 8, 2],
       [8, 6, 4, 0, 4, 0, 4, 8, 3, 7],
       [8, 2, 4, 7, 7, 6, 5, 5, 9, 7],
       [0, 1, 2, 6, 4, 7, 0, 4, 0, 4],
       [6, 4, 5, 5, 5, 8, 9, 7, 0, 9],
       [3, 2, 7, 2, 8, 5, 5, 1, 3, 9],
       [3, 9, 3, 0, 6, 0, 8, 2, 4, 3],
       [2, 1, 0, 7, 1, 8, 3, 8, 8, 4],
       [1, 1, 1, 0, 4, 7, 5, 0, 3, 5],
       [5, 1, 2, 1, 4, 6, 3, 5, 5, 0]])

In [123]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
x=np.random.randint(0,10,(10,10))
x

array([[0, 6, 1, 9, 6, 8, 1, 3, 9, 4],
       [0, 9, 1, 6, 3, 4, 6, 2, 1, 8],
       [2, 3, 0, 7, 7, 7, 1, 8, 0, 8],
       [9, 9, 4, 6, 3, 4, 6, 7, 0, 0],
       [9, 3, 2, 8, 9, 2, 6, 5, 9, 2],
       [6, 6, 2, 1, 2, 0, 7, 6, 8, 8],
       [7, 0, 6, 0, 9, 0, 0, 8, 1, 7],
       [1, 7, 1, 8, 1, 4, 9, 2, 4, 8],
       [3, 5, 4, 2, 3, 7, 9, 4, 7, 6],
       [9, 2, 8, 5, 0, 4, 2, 1, 0, 9]])

In [125]:
np.median(x)

4.0

In [128]:
x.mean()

4.52

In [130]:
x[x.min()]

array([0, 6, 1, 9, 6, 8, 1, 3, 9, 4])

In [131]:
x.std()

3.1192306743811042

In [132]:
x.var()

9.7296