In [2]:
a=2
b=2.6
c="data science"
type(a),type(b),type(c)

(int, float, str)

In [7]:
c

'data science'

In [ ]:
  -11----------2-1
 'data science'
  01234567891011


In [9]:
c[0], c[0:4],c[-4:-1],c[-4:]

('d', 'data', 'enc')

In [11]:
c.upper(),c.lower(),c.capitalize(),c.isupper(),c.islower()

('DATA SCIENCE', 'data science', 'Data science', False, True)

In [13]:
c.isalpha(),c.isalnum(),c.isdigit(),c.endswith("e"),c.startswith("d")

(False, False, False, True, True)

In [14]:
c

'data science'

In [16]:
### list and numpy

In [17]:
x=[1,2,3,"data science"]

In [19]:
x[-1][-1]

'e'

In [20]:
x=[1,2,3]

In [21]:
type(x)

list

In [22]:
x/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [23]:
import numpy as np

In [24]:
y=np.array(x)

In [26]:
y/2

array([0.5, 1. , 1.5])

In [28]:
x=np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]])

In [29]:
x

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [62]:
x=np.random.randint(10,100,(9,4))

In [66]:
x[0:4,2:]

array([[57, 25],
       [87, 78],
       [37, 81],
       [27, 26]])

In [67]:
x[:,1]

array([48, 82, 92, 99, 25, 53, 51, 27, 71])

In [75]:
np.sqrt(((x[0]-x)*(x[0]-x)).sum(axis=1)[1:]).argmin()

4

In [73]:
((x[0]-x)*(x[0]-x))

array([[   0,    0,    0,    0],
       [ 196, 1156,  900, 2809],
       [1521, 1936,  400, 3136],
       [1369, 2601,  900,    1],
       [2025,  529,  729, 2704],
       [   9,   25,  900,  100],
       [1089,    9, 1024,  484],
       [  36,  441, 1089, 2401],
       [ 484,  529,  361, 1521]])