In [31]:
#String
x = 'Data'
print(x.upper())
print(x.lower())
print(x.isupper())
print('data'.islower())
print(len(x))
print(x.isalpha())
print('1234'.isnumeric())
print(x.isalnum())
print('test\n'.isspace())
print(x.startswith('D'))
print(x.endswith('a'))
print(x.index('t'))
#print(x.index('p'))
print(x.find('t'))
print(x.find('p'))
print(x.count('a'))
print('Sridhar vuttarkar'.center(20,'a'))

DATA
data
False
True
4
True
True
True
False
True
True
2
2
-1
2
aSridhar vuttarkaraa


In [24]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [26]:
a = 'Data science'
print(a[2])
print(a[-2])

t
c


In [1]:
import numpy as np
a = np.array([[1, 2, 3],[4,5,6],[7,8,9]])
print(a[:,:])
print("----------------------------------------")
print(a[0:1,:])
print("----------------------------------------")
print(a[2:,2:])
print("----------------------------------------")
print(a[0:2,1:])
print("----------------------------------------")
print(a[0]-a)
print("----------------------------------------")
print((a[0]-a)**2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------
[[1 2 3]]
----------------------------------------
[[9]]
----------------------------------------
[[2 3]
 [5 6]]
----------------------------------------
[[ 0  0  0]
 [-3 -3 -3]
 [-6 -6 -6]]
----------------------------------------
[[ 0  0  0]
 [ 9  9  9]
 [36 36 36]]
