In [1]:
import pandas as pd
base_dataset=pd.read_csv("C:\\Sridhar\\AI_ML\\Python\\Python-20191004T130356Z-001\\Python\\36- Datasets\\titanic\\test.csv")

In [2]:
import numpy as np

In [3]:
base_dataset.shape

(418, 11)

In [6]:
dataset=base_dataset.sample(50)

In [7]:
dataset.shape

(50, 11)

In [8]:
dataset.values[0]

array([1093, 3, 'Danbom, Master. Gilbert Sigvard Emanuel', 'male', 0.33,
       0, 2, '347080', 14.4, nan, 'S'], dtype=object)

In [9]:
dataset=dataset[['Age','Fare']]

In [10]:
dataset.shape

(50, 2)

In [22]:
r1=dataset[0:1].values

In [23]:
r2=dataset[10:11].values

In [24]:
r3=dataset[20:21].values

In [25]:
for i in dataset:
    dataset[i].fillna(dataset[i].median(),inplace=True)

In [26]:
d1=np.sqrt(((r1-dataset)*(r1-dataset)).sum(axis=1))

In [27]:
d2=np.sqrt(((r2-dataset)*(r2-dataset)).sum(axis=1))

In [28]:
d3=np.sqrt(((r3-dataset)*(r3-dataset)).sum(axis=1))

In [29]:
distance_data=list(zip(d1,d2,d3))

In [30]:
distance_data=np.array(distance_data)

In [32]:
distance_data.argmin(axis=1)

array([0, 1, 1, 2, 1, 1, 1, 0, 0, 2, 1, 2, 2, 1, 1, 0, 1, 0, 1, 1, 2, 1,
       2, 2, 2, 2, 2, 1, 2, 1, 1, 0, 2, 2, 1, 2, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 2, 1, 1], dtype=int64)

In [132]:
dataset[distance_data.argmin(axis=1)==0].shape,dataset[distance_data.argmin(axis=1)==1].shape,dataset[distance_data.argmin(axis=1)==2].shape

((7, 2), (26, 2), (17, 2))

In [ ]:
# Find the centroid

In [133]:
c1=dataset[distance_data.argmin(axis=1)==0]
c2=dataset[distance_data.argmin(axis=1)==1]
c3=dataset[distance_data.argmin(axis=1)==2]

In [134]:
r1_c1=c1.mean(axis=0)
r2_c2=c2.mean(axis=0)
r3_c3=c3.mean(axis=0)

In [135]:
d1=np.sqrt(((r1_c1-dataset)*(r1_c1-dataset)).sum(axis=1))
d2=np.sqrt(((r2_c2-dataset)*(r2_c2-dataset)).sum(axis=1))
d3=np.sqrt(((r3_c3-dataset)*(r3_c3-dataset)).sum(axis=1))

In [136]:
distance=list(zip(d1,d2,d3))

In [137]:
distance=np.array(distance)

In [138]:
distance.argmin(axis=1)

array([0, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 1, 1, 1, 0, 2, 2, 1, 2, 2, 0, 0,
       0, 2, 0, 0, 1, 0, 2, 2, 1, 0, 2, 1, 0, 1, 2, 1, 2, 2, 1, 2, 2, 2,
       1, 2, 2, 0, 2, 1], dtype=int64)