In [1]:
import pandas as pd
import numpy as np

In [2]:
data=np.random.randint(0,3,(20,5))

In [3]:
data

array([[0, 2, 0, 2, 2],
       [0, 0, 0, 2, 1],
       [1, 1, 2, 0, 1],
       [0, 0, 0, 0, 2],
       [1, 0, 1, 0, 2],
       [2, 1, 0, 1, 0],
       [0, 2, 2, 2, 1],
       [0, 2, 0, 2, 1],
       [1, 1, 0, 0, 1],
       [1, 0, 2, 1, 1],
       [2, 1, 2, 1, 2],
       [2, 0, 2, 0, 2],
       [2, 1, 0, 1, 0],
       [1, 0, 2, 1, 0],
       [2, 2, 2, 0, 2],
       [2, 0, 0, 0, 2],
       [2, 2, 0, 2, 1],
       [0, 0, 2, 2, 0],
       [2, 1, 0, 0, 1],
       [2, 2, 2, 2, 0]])

In [4]:
data[0],data[12],data[17]

(array([0, 2, 0, 2, 2]), array([2, 1, 0, 1, 0]), array([0, 0, 2, 2, 0]))

In [5]:
data[0]==data

array([[ True,  True,  True,  True,  True],
       [ True, False,  True,  True, False],
       [False, False, False, False, False],
       [ True, False,  True, False,  True],
       [False, False, False, False,  True],
       [False, False,  True, False, False],
       [ True,  True, False,  True, False],
       [ True,  True,  True,  True, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False,  True],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False,  True, False, False,  True],
       [False, False,  True, False,  True],
       [False,  True,  True,  True, False],
       [ True, False, False,  True, False],
       [False, False,  True, False, False],
       [False,  True, False,  True, False]])

In [6]:
(data[0]==data).sum(axis=1)

array([5, 3, 0, 3, 1, 1, 3, 4, 1, 0, 1, 1, 1, 0, 2, 2, 3, 2, 1, 2])

In [7]:
data.shape[1]

5

In [8]:
d1 = data.shape[1] - (data[0]==data).sum(axis=1)
d2 = data.shape[1] - (data[12]==data).sum(axis=1)
d3 = data.shape[1] - (data[17]==data).sum(axis=1)

In [9]:
d1,d2,d3

(array([0, 2, 5, 2, 4, 4, 2, 1, 4, 5, 4, 4, 4, 5, 3, 3, 2, 3, 4, 3]),
 array([4, 4, 4, 4, 5, 0, 5, 4, 3, 4, 2, 4, 0, 3, 4, 3, 3, 4, 2, 3]),
 array([3, 2, 4, 3, 4, 4, 2, 3, 5, 3, 4, 3, 4, 2, 4, 4, 4, 0, 5, 2]))

In [10]:
clusters=list(zip(d1,d2,d3))

In [11]:
clusters=np.array(clusters)

In [12]:
clusters

array([[0, 4, 3],
       [2, 4, 2],
       [5, 4, 4],
       [2, 4, 3],
       [4, 5, 4],
       [4, 0, 4],
       [2, 5, 2],
       [1, 4, 3],
       [4, 3, 5],
       [5, 4, 3],
       [4, 2, 4],
       [4, 4, 3],
       [4, 0, 4],
       [5, 3, 2],
       [3, 4, 4],
       [3, 3, 4],
       [2, 3, 4],
       [3, 4, 0],
       [4, 2, 5],
       [3, 3, 2]])

In [14]:
clusters.argmin(axis=1)==0

array([ True,  True, False,  True,  True, False,  True,  True, False,
       False, False, False, False, False,  True,  True,  True, False,
       False, False])

In [17]:
c1=data[clusters.argmin(axis=1)==0]
c2=data[clusters.argmin(axis=1)==1]
c3=data[clusters.argmin(axis=1)==2]

In [18]:
c1

array([[0, 2, 0, 2, 2],
       [0, 0, 0, 2, 1],
       [0, 0, 0, 0, 2],
       [1, 0, 1, 0, 2],
       [0, 2, 2, 2, 1],
       [0, 2, 0, 2, 1],
       [2, 2, 2, 0, 2],
       [2, 0, 0, 0, 2],
       [2, 2, 0, 2, 1]])

In [19]:
c2

array([[1, 1, 2, 0, 1],
       [2, 1, 0, 1, 0],
       [1, 1, 0, 0, 1],
       [2, 1, 2, 1, 2],
       [2, 1, 0, 1, 0],
       [2, 1, 0, 0, 1]])

In [20]:
c3

array([[1, 0, 2, 1, 1],
       [2, 0, 2, 0, 2],
       [1, 0, 2, 1, 0],
       [0, 0, 2, 2, 0],
       [2, 2, 2, 2, 0]])

In [21]:
mode_c1=pd.DataFrame(c1).mode().values
mode_c2=pd.DataFrame(c2).mode().values[0]
mode_c3=pd.DataFrame(c3).mode().values[0]

In [22]:
mode_c1,mode_c2,mode_c3

(array([[0, 2, 0, 2, 2]]),
 array([2., 1., 0., 0., 1.]),
 array([1., 0., 2., 1., 0.]))

In [23]:
d1=data.shape[1]-(mode_c1==data).sum(axis=1)
d2=data.shape[1]-(mode_c2==data).sum(axis=1)
d3=data.shape[1]-(mode_c3==data).sum(axis=1)

In [24]:
d1

array([0, 2, 5, 2, 4, 4, 2, 1, 4, 5, 4, 4, 4, 5, 3, 3, 2, 3, 4, 3])

In [25]:
d3

array([5, 4, 3, 4, 3, 3, 4, 5, 4, 1, 3, 3, 3, 0, 4, 4, 5, 2, 5, 3])

In [26]:
d3

array([5, 4, 3, 4, 3, 3, 4, 5, 4, 1, 3, 3, 3, 0, 4, 4, 5, 2, 5, 3])

In [27]:
clusters=list(zip(d1,d2,d3))

In [28]:
clusters=np.array(clusters)

In [29]:
clusters

array([[0, 4, 5],
       [2, 3, 4],
       [5, 2, 3],
       [2, 3, 4],
       [4, 4, 3],
       [4, 2, 3],
       [2, 4, 4],
       [1, 3, 5],
       [4, 1, 4],
       [5, 4, 1],
       [4, 3, 3],
       [4, 3, 3],
       [4, 2, 3],
       [5, 5, 0],
       [3, 3, 4],
       [3, 2, 4],
       [2, 2, 5],
       [3, 5, 2],
       [4, 0, 5],
       [3, 4, 3]])

In [30]:
c1_1=data[clusters.argmin(axis=1)==0]
c1_2=data[clusters.argmin(axis=1)==1]
c1_3=data[clusters.argmin(axis=1)==2]


In [31]:
c1_1.shape

(8, 5)

In [32]:
c1.shape

(9, 5)

In [33]:
pip install kmodes

Note: you may need to restart the kernel to use updated packages.


In [34]:
from kmodes.kmodes import KModes
# random categorical data
data = np.random.choice(20,(100,10))
km = KModes(n_clusters=4)
clusters1 = km.fit_predict(data)
# Print the cluster centroids
print(clusters1)

[3 2 1 0 2 1 1 2 0 1 0 3 0 1 0 1 0 1 0 0 0 1 0 1 1 0 1 0 1 1 2 0 2 0 3 1 3
 1 0 0 2 3 1 3 0 2 3 2 2 1 1 0 0 1 0 0 2 3 0 2 0 3 2 0 1 0 0 0 2 2 1 0 0 2
 2 0 3 2 0 1 0 1 2 1 1 2 1 1 2 0 2 2 0 0 0 0 0 2 1 3]
