In [2]:
import numpy as np
import pandas as pd

In [3]:
base_dataset=pd.read_csv("C:\\Sridhar\\AI_ML\\Python\\Pandas\\file1\\application_train.csv")

In [4]:
base_dataset = base_dataset[base_dataset.describe().columns]

In [5]:
# base_dataset = base_dataset[0:20]

In [6]:
base_dataset.shape

(307511, 106)

In [27]:
# base_dataset = base_dataset[0:100]

In [7]:
base_dataset.head()

SK_ID_CURR  TARGET  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
0      100002       1             0          202500.0    406597.5   
1      100003       0             0          270000.0   1293502.5   
2      100004       0             0           67500.0    135000.0   
3      100006       0             0          135000.0    312682.5   
4      100007       0             0          121500.0    513000.0   

   AMT_ANNUITY  AMT_GOODS_PRICE  REGION_POPULATION_RELATIVE  DAYS_BIRTH  \
0      24700.5         351000.0                    0.018801       -9461   
1      35698.5        1129500.0                    0.003541      -16765   
2       6750.0         135000.0                    0.010032      -19046   
3      29686.5         297000.0                    0.008019      -19005   
4      21865.5         513000.0                    0.028663      -19932   

   DAYS_EMPLOYED  ...  FLAG_DOCUMENT_18  FLAG_DOCUMENT_19  FLAG_DOCUMENT_20  \
0           -637  ...                 0                 0                 0   
1          -1188  ...                 0                 0                 0   
2           -225  ...                 0                 0                 0   
3          -3039  ...                 0                 0                 0   
4          -3038  ...                 0                 0                 0   

   FLAG_DOCUMENT_21  AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  \
0                 0                         0.0                        0.0   
1                 0                         0.0                        0.0   
2                 0                         0.0                        0.0   
3                 0                         NaN                        NaN   
4                 0                         0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        0.0   
3                         NaN                        NaN   
4                         0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        0.0                         1.0  
1                        0.0                         0.0  
2                        0.0                         0.0  
3                        NaN                         NaN  
4                        0.0                         0.0  

[5 rows x 106 columns]

In [28]:
# base_dataset.shape

In [8]:
base_dataset=base_dataset[base_dataset.var().sort_values().tail(20).index]

In [9]:
base_dataset.shape

(307511, 20)

In [18]:
base_dataset=base_dataset[0:10]

In [19]:
base_dataset.shape

(10, 20)

In [20]:
for i in base_dataset.columns:
    base_dataset[i].fillna(base_dataset[i].median(),inplace=True)

for i in base_dataset.columns:
    base_dataset[i].fillna(base_dataset[i].mode().values[0],inplace=True)
    
# for i in base_dataset.columns:
#     base_dataset[i].base_dataset(base_dataset[i].mode().values[0],inplace=True)

In [21]:
y=base_dataset['AMT_CREDIT']

In [22]:
x=base_dataset.drop('AMT_CREDIT',axis=1)

In [23]:
x

REGION_RATING_CLIENT  CNT_CHILDREN  AMT_REQ_CREDIT_BUREAU_QRT  \
0                     2             0                        0.0   
1                     1             0                        0.0   
2                     2             0                        0.0   
3                     2             0                        0.0   
4                     2             0                        0.0   
5                     2             0                        1.0   
6                     2             1                        1.0   
7                     3             0                        0.0   
8                     2             0                        0.0   
9                     2             0                        0.0   

   CNT_FAM_MEMBERS  AMT_REQ_CREDIT_BUREAU_MON  AMT_REQ_CREDIT_BUREAU_YEAR  \
0              1.0                        0.0                         1.0   
1              2.0                        0.0                         0.0   
2              1.0                        0.0                         0.0   
3              2.0                        0.0                         1.0   
4              1.0                        0.0                         0.0   
5              2.0                        0.0                         1.0   
6              3.0                        1.0                         2.0   
7              2.0                        0.0                         0.0   
8              2.0                        0.0                         1.0   
9              1.0                        0.0                         1.0   

   OBS_60_CNT_SOCIAL_CIRCLE  OBS_30_CNT_SOCIAL_CIRCLE  \
0                       2.0                       2.0   
1                       1.0                       1.0   
2                       0.0                       0.0   
3                       2.0                       2.0   
4                       0.0                       0.0   
5                       0.0                       0.0   
6                       1.0                       1.0   
7                       2.0                       2.0   
8                       1.0                       1.0   
9                       2.0                       2.0   

   HOUR_APPR_PROCESS_START  OWN_CAR_AGE  DAYS_LAST_PHONE_CHANGE  \
0                       10          9.0                 -1134.0   
1                       11          9.0                  -828.0   
2                        9         26.0                  -815.0   
3                       17          9.0                  -617.0   
4                       11          9.0                 -1106.0   
5                       16          9.0                 -2536.0   
6                       16         17.0                 -1562.0   
7                       16          8.0                 -1070.0   
8                       14          9.0                     0.0   
9                        8          9.0                 -1673.0   

   DAYS_ID_PUBLISH  DAYS_REGISTRATION  DAYS_BIRTH  AMT_ANNUITY  SK_ID_CURR  \
0            -2120            -3648.0       -9461      24700.5      100002   
1             -291            -1186.0      -16765      35698.5      100003   
2            -2531            -4260.0      -19046       6750.0      100004   
3            -2437            -9833.0      -19005      29686.5      100006   
4            -3458            -4311.0      -19932      21865.5      100007   
5             -477            -4970.0      -16941      27517.5      100008   
6             -619            -1213.0      -13778      41301.0      100009   
7            -2379            -4597.0      -18850      42075.0      100010   
8            -3514            -7427.0      -20099      33826.5      100011   
9            -3992           -14437.0      -14469      20250.0      100012   

   DAYS_EMPLOYED  AMT_INCOME_TOTAL  AMT_GOODS_PRICE  
0           -637          202500.0         351000.0  
1          -1188          270000.0        1129500.0  
2           -225   

In [24]:
## Calulate beta coefficient

In [25]:
x=x.values

In [26]:
x

array([[ 2.00000e+00,  0.00000e+00,  0.00000e+00,  1.00000e+00,
         0.00000e+00,  1.00000e+00,  2.00000e+00,  2.00000e+00,
         1.00000e+01,  9.00000e+00, -1.13400e+03, -2.12000e+03,
        -3.64800e+03, -9.46100e+03,  2.47005e+04,  1.00002e+05,
        -6.37000e+02,  2.02500e+05,  3.51000e+05],
       [ 1.00000e+00,  0.00000e+00,  0.00000e+00,  2.00000e+00,
         0.00000e+00,  0.00000e+00,  1.00000e+00,  1.00000e+00,
         1.10000e+01,  9.00000e+00, -8.28000e+02, -2.91000e+02,
        -1.18600e+03, -1.67650e+04,  3.56985e+04,  1.00003e+05,
        -1.18800e+03,  2.70000e+05,  1.12950e+06],
       [ 2.00000e+00,  0.00000e+00,  0.00000e+00,  1.00000e+00,
         0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,
         9.00000e+00,  2.60000e+01, -8.15000e+02, -2.53100e+03,
        -4.26000e+03, -1.90460e+04,  6.75000e+03,  1.00004e+05,
        -2.25000e+02,  6.75000e+04,  1.35000e+05],
       [ 2.00000e+00,  0.00000e+00,  0.00000e+00,  2.00000e+00,
         0.0000

In [27]:
x.shape

(10, 19)

In [28]:
x.T.shape

(19, 10)

In [30]:
x.T

array([[ 2.00000e+00,  1.00000e+00,  2.00000e+00,  2.00000e+00,
         2.00000e+00,  2.00000e+00,  2.00000e+00,  3.00000e+00,
         2.00000e+00,  2.00000e+00],
       [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,
         0.00000e+00,  0.00000e+00,  1.00000e+00,  0.00000e+00,
         0.00000e+00,  0.00000e+00],
       [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,
         0.00000e+00,  1.00000e+00,  1.00000e+00,  0.00000e+00,
         0.00000e+00,  0.00000e+00],
       [ 1.00000e+00,  2.00000e+00,  1.00000e+00,  2.00000e+00,
         1.00000e+00,  2.00000e+00,  3.00000e+00,  2.00000e+00,
         2.00000e+00,  1.00000e+00],
       [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,
         0.00000e+00,  0.00000e+00,  1.00000e+00,  0.00000e+00,
         0.00000e+00,  0.00000e+00],
       [ 1.00000e+00,  0.00000e+00,  0.00000e+00,  1.00000e+00,
         0.00000e+00,  1.00000e+00,  2.00000e+00,  0.00000e+00,
         1.00000e+00,  1.00000e+00],
       [ 2

In [31]:
q = np.dot(x,x.T)

In [32]:
q

array([[1.74926769e+11, 4.62177024e+11, 7.14232467e+10, 1.42542051e+11,
        2.15422563e+11, 1.90441004e+11, 5.35433612e+11, 6.21172126e+11,
        3.54248622e+11, 1.80195289e+11],
       [4.62177024e+11, 1.36022989e+12, 1.81275202e+11, 3.83307275e+11,
        6.23364870e+11, 5.51365219e+11, 1.63353570e+12, 1.83716190e+12,
        1.07329509e+12, 5.04886535e+11],
       [7.14232467e+10, 1.81275202e+11, 3.32156318e+10, 5.98200968e+10,
        8.80132694e+10, 7.85744055e+10, 2.10418710e+11, 2.41521001e+11,
        1.41487238e+11, 7.42747876e+10],
       [1.42542051e+11, 3.83307275e+11, 5.98200968e+10, 1.17789922e+11,
        1.79853450e+11, 1.59548185e+11, 4.48913345e+11, 5.14671929e+11,
        2.96856492e+11, 1.49546791e+11],
       [2.15422563e+11, 6.23364870e+11, 8.80132694e+10, 1.79853450e+11,
        2.88849030e+11, 2.56158557e+11, 7.47609397e+11, 8.39958001e+11,
        4.92370858e+11, 2.34984599e+11],
       [1.90441004e+11, 5.51365219e+11, 7.85744055e+10, 1.59548185e+11,
   

In [39]:
q.shape

(10, 10)

In [40]:
from numpy.linalg import inv
p = inv(q)

In [41]:
p

array([[ 1.72741376e-04, -9.61394924e-04,  5.68031231e-04,
         3.07584940e-04, -6.92185814e-04,  1.18685146e-04,
         2.55619325e-04,  6.31554091e-04, -4.38157816e-06,
        -3.96268697e-04],
       [-9.61394924e-04,  5.35104165e-03, -3.16174567e-03,
        -1.71206480e-03,  3.85289108e-03, -6.60665370e-04,
        -1.42275349e-03, -3.51523396e-03,  2.43887099e-05,
         2.20562037e-03],
       [ 5.68031231e-04, -3.16174567e-03,  1.86836907e-03,
         1.01179224e-03, -2.27683190e-03,  3.90238536e-04,
         8.40752633e-04,  2.07704499e-03, -1.44112435e-05,
        -1.30328908e-03],
       [ 3.07584940e-04, -1.71206480e-03,  1.01179224e-03,
         5.48006955e-04, -1.23297770e-03,  2.11170128e-04,
         4.55331181e-04,  1.12469234e-03, -7.80345696e-06,
        -7.05758567e-04],
       [-6.92185814e-04,  3.85289108e-03, -2.27683190e-03,
        -1.23297770e-03,  2.77464357e-03, -4.75590460e-04,
        -1.02453831e-03, -2.53109802e-03,  1.75620380e-05,
         1.

In [43]:
pd.DataFrame(p).shape

(10, 10)

In [44]:
B = x.T*p*y

ValueError: operands could not be broadcast together with shapes (19,10) (10,10) 

In [45]:
h = np.dot(x.T,p)

In [46]:
beta = np.dot(h,y) # beta = inverse(x.x.T)*xt*y

In [47]:
beta

array([-8.95226066e+02, -1.43648777e+02, -2.10372035e+02, -3.39040749e+02,
       -1.43648777e+02, -3.98785954e+02, -4.05217834e+02, -4.05217834e+02,
       -3.78876544e+03, -6.22114242e+03,  8.30180151e+01,  5.22315928e+01,
       -4.06657700e+00,  9.78544916e+00, -3.45857918e+00,  6.18709952e+00,
       -8.90025244e-02, -8.49868342e-01,  1.21364960e+00])

In [69]:
beta.shape

(19,)

In [70]:
beta1 = dot((np.dot(x.T,inv(np.dot(x,x.T)))),y)

NameError: name 'dot' is not defined

In [3]:
import pandas as pd
sr = pd.Series(['New York', 'Chicago', 'Toronto', 'Lisbon', 'Rio', 'Chicago', 'Lisbon']) 
print(sr)

0    New York
1     Chicago
2     Toronto
3      Lisbon
4         Rio
5     Chicago
6      Lisbon
dtype: object


In [4]:
sr.value_counts()

Chicago     2
Lisbon      2
New York    1
Toronto     1
Rio         1
dtype: int64

In [8]:
sr.value_counts(normalize=True).values

array([0.28571429, 0.28571429, 0.14285714, 0.14285714, 0.14285714])