# import numpy as np
x = np.arange(1,11)
y = np.arange(11,21)
print(x)
print(y)
d1 = x - x.mean()
d2 = y - y.mean()

d12 = d1*d2

print(d1)
print(d2)
print(d12)


In [13]:
import numpy as np
x = np.arange(1,11) 
y = np.arange(11,21) 
print(x) 
print(y) 
d1 = x - x.mean() 
d2 = y - y.mean()
d12 = d1*d2
print(d1) 
print(d2) 
print(d12)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
[-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
[-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
[20.25 12.25  6.25  2.25  0.25  0.25  2.25  6.25 12.25 20.25]


In [16]:
np.sqrt(((d1*d1).sum())*((d2*d2.sum())))
#d12.sum()/np.sqrt(((d1*d1).sum())*((d2*d2.sum())))

array([-0., -0., -0., -0., -0.,  0.,  0.,  0.,  0.,  0.])